const TOURS = [
  {
    slug: "varanasi-tour",
    title: "Varanasi Tour",
    pageTitle: "Varanasi 3 Days / 2 Nights Tour Package",
    tagline: "Explore the Spiritual Heart of Varanasi",
    duration: "3 Days / 2 Nights",
    destination: "Varanasi, Uttar Pradesh",
    price: "₹9,999",
    priceLabel: "Starting From ₹9,999",
    image: "https://images.unsplash.com/photo-1558184525-2218e8c34914?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cardImage: "https://images.unsplash.com/photo-1558184525-2218e8c34914?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    url: "tours/varanasi-tour.html",
    intro:
      "Varanasi के इस 3 Days / 2 Nights Tour Package में आपको Spirituality, Culture और Heritage का पूरा अनुभव मिलेगा। इस पैकेज में Temple Darshan, Ganga Aarti, Boat Ride, Sarnath Visit और Local Market Experience शामिल है।",
    days: [
      {
        title: "Day 1 – Arrival + Temple Darshan + Ganga Aarti",
        items: [
          "Varanasi Airport / Railway Station से Pickup",
          "Hotel Transfer & Check-in",
          "Freshen up & Rest",
          "Kashi Vishwanath Temple Darshan",
          "Kaal Bhairav Temple Visit",
          "Mahamrityunjay Temple Visit",
          "शाम को Ganga Ghat पर विश्व प्रसिद्ध Ganga Aarti का अनुभव",
          "Overnight Stay in Varanasi",
        ],
      },
      {
        title: "Day 2 – Sarnath + Subah-e-Banaras + Ganga Boat Ride",
        items: [
          "Morning: Subah-e-Banaras (Assi Ghat Experience)",
          "Breakfast",
          "Sarnath Sightseeing (Buddhist Heritage Site)",
          "Evening: Ganga River Boat Ride",
          "Assi Ghat to Dashashwamedh Ghat या Namo Ghat to Dashashwamedh Ghat",
          "Ghats और Evening Varanasi का सुंदर दृश्य",
          "Overnight Stay in Varanasi",
        ],
      },
      {
        title: "Day 3 – Temple Tour + Local Market + Departure",
        items: [
          "Durga Mata Temple Visit (Durgakund)",
          "Sankat Mochan Hanuman Temple",
          "BHU (Birla Temple) Visit",
          "Tridev Temple",
          "Local Market Visit (Godowlia Market)",
          "Banarasi Saree Shopping Experience",
          "Local Handicrafts & Cultural Shopping",
          "Varanasi Airport / Railway Station Drop",
        ],
      },
    ],
    inclusions: [
      "Hotel Stay (1/2/3 Star Category – Availability के अनुसार)",
      "Pickup & Drop (Airport / Railway Station)",
      "Local Sightseeing Transport",
      "Ganga Boat Ride (Standard Route)",
      "Local Guide Assistance (Tour Support)",
    ],
    exclusions: [
      "Food / Meals (Breakfast, Lunch, Dinner शामिल नहीं है)",
      "Kashi Vishwanath Temple VIP Pass (Self Paid)",
      "Personal Expenses (Shopping, Tips, etc.)",
      "Entry Fees (जहाँ applicable हो)",
    ],
    highlights: [
      "3 Days / 2 Nights Complete Varanasi Tour",
      "Kashi Vishwanath Temple Darshan",
      "Ganga Aarti Experience",
      "Sarnath Buddhist Tour",
      "Ganga Boat Ride",
      "Local Market & Banarasi Saree Shopping",
      "Comfortable Travel & Stay Arrangement",
    ],
    cta: "Book your Varanasi Tour and experience the divine city of Kashi with full comfort and spiritual vibes.",
  },
  {
    slug: "varanasi-ayodhya-tour",
    title: "Varanasi – Ayodhya Tour",
    pageTitle: "Varanasi – Ayodhya 4 Days / 3 Nights Tour Package",
    tagline: "Experience Kashi & the Birthplace of Lord Rama",
    duration: "4 Days / 3 Nights",
    destination: "Varanasi & Ayodhya, Uttar Pradesh",
    price: "₹14,999",
    priceLabel: "Starting From ₹14,999",
    image: "https://images.unsplash.com/photo-1726501604891-19fb7f7cd37b?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cardImage: "https://images.unsplash.com/photo-1726501604891-19fb7f7cd37b?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    url: "tours/varanasi-ayodhya-tour.html",
    intro:
      "इस 4 Days / 3 Nights Tour Package में Varanasi की Spiritual Journey के साथ Ayodhya — Lord Rama की Janmabhoomi का दिव्य अनुभव शामिल है। Temple Darshan, Ganga Aarti, Sarnath Visit और Ayodhya Ram Mandir Darshan इस पैकेज की मुख्य highlights हैं।",
    days: [
      {
        title: "Day 1 – Arrival in Varanasi + Temple Darshan + Ganga Aarti",
        items: [
          "Varanasi Airport / Railway Station से Pickup",
          "Hotel Transfer & Check-in",
          "Kashi Vishwanath Temple Darshan",
          "Kaal Bhairav Temple Visit",
          "शाम को Dashashwamedh Ghat पर Ganga Aarti",
          "Overnight Stay in Varanasi",
        ],
      },
      {
        title: "Day 2 – Sarnath + Subah-e-Banaras + Ganga Boat Ride",
        items: [
          "Morning: Subah-e-Banaras (Assi Ghat Experience)",
          "Sarnath Sightseeing (Dhamek Stupa, Buddhist Temples)",
          "Evening: Ganga River Boat Ride",
          "Local Market Visit (Godowlia)",
          "Overnight Stay in Varanasi",
        ],
      },
      {
        title: "Day 3 – Varanasi to Ayodhya + Ram Mandir Darshan",
        items: [
          "Early Morning Departure to Ayodhya",
          "Hotel Check-in at Ayodhya",
          "Shri Ram Janmabhoomi Temple Darshan",
          "Hanuman Garhi Temple Visit",
          "Kanak Bhawan Temple",
          "Saryu Ghat Evening Aarti",
          "Overnight Stay in Ayodhya",
        ],
      },
      {
        title: "Day 4 – Ayodhya Sightseeing + Departure",
        items: [
          "Nageshwarnath Temple Visit",
          "Local Ayodhya Market & Prasad Shopping",
          "Return Journey to Varanasi",
          "Varanasi Airport / Railway Station Drop",
        ],
      },
    ],
    inclusions: [
      "Hotel Stay in Varanasi & Ayodhya (1/2/3 Star – Availability के अनुसार)",
      "Pickup & Drop (Airport / Railway Station)",
      "Inter-city Transport (Varanasi ↔ Ayodhya)",
      "Local Sightseeing Transport",
      "Ganga Boat Ride in Varanasi",
      "Local Guide Assistance (Tour Support)",
    ],
    exclusions: [
      "Food / Meals (Breakfast, Lunch, Dinner शामिल नहीं है)",
      "Temple VIP Pass / Special Darshan (Self Paid)",
      "Personal Expenses (Shopping, Tips, etc.)",
      "Entry Fees (जहाँ applicable हो)",
    ],
    highlights: [
      "4 Days / 3 Nights Varanasi + Ayodhya Tour",
      "Kashi Vishwanath & Ganga Aarti Experience",
      "Sarnath Buddhist Heritage Tour",
      "Shri Ram Janmabhoomi Temple Darshan",
      "Hanuman Garhi & Kanak Bhawan Visit",
      "Saryu River Ghat Experience",
      "Comfortable Travel & Stay Arrangement",
    ],
    cta: "Book your Varanasi – Ayodhya Tour and experience the spiritual journey of Kashi and Ram Janmabhoomi.",
  },
  {
    slug: "varanasi-ayodhya-prayag-tour",
    title: "Varanasi – Ayodhya – Prayag Tour",
    pageTitle: "Varanasi – Ayodhya – Prayag 5 Days / 4 Nights Tour Package",
    tagline: "The Ultimate Spiritual Triangle of Uttar Pradesh",
    duration: "5 Days / 4 Nights",
    destination: "Varanasi, Ayodhya & Prayagraj, Uttar Pradesh",
    price: "₹19,999",
    priceLabel: "Starting From ₹19,999",
    image: "https://images.unsplash.com/photo-1742316963892-2b6fee25dfc5?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cardImage: "https://images.unsplash.com/photo-1742316963892-2b6fee25dfc5?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    url: "tours/varanasi-ayodhya-prayag-tour.html",
    intro:
      "यह 5 Days / 4 Nights Tour Package Uttar Pradesh की तीन सबसे पवित्र cities — Varanasi, Ayodhya और Prayagraj (Allahabad) का complete spiritual experience देता है। Kashi Darshan, Ram Janmabhoomi और Triveni Sangam Snan इस यात्रा की मुख्य विशेषताएँ हैं।",
    days: [
      {
        title: "Day 1 – Arrival in Varanasi + Temple Darshan + Ganga Aarti",
        items: [
          "Varanasi Airport / Railway Station से Pickup",
          "Hotel Transfer & Check-in",
          "Kashi Vishwanath Temple Darshan",
          "Kaal Bhairav Temple Visit",
          "शाम को Ganga Aarti at Dashashwamedh Ghat",
          "Overnight Stay in Varanasi",
        ],
      },
      {
        title: "Day 2 – Sarnath + Subah-e-Banaras + Ganga Boat Ride",
        items: [
          "Morning: Subah-e-Banaras (Assi Ghat Experience)",
          "Sarnath Sightseeing (Buddhist Heritage Site)",
          "Evening: Ganga River Boat Ride",
          "Durga Temple & Sankat Mochan Hanuman Temple",
          "Overnight Stay in Varanasi",
        ],
      },
      {
        title: "Day 3 – Varanasi to Ayodhya + Ram Mandir Darshan",
        items: [
          "Morning Departure to Ayodhya",
          "Shri Ram Janmabhoomi Temple Darshan",
          "Hanuman Garhi & Kanak Bhawan Temple",
          "Saryu Ghat Evening Aarti",
          "Overnight Stay in Ayodhya",
        ],
      },
      {
        title: "Day 4 – Ayodhya to Prayagraj + Sangam Snan",
        items: [
          "Morning Departure to Prayagraj",
          "Hotel Check-in at Prayagraj",
          "Triveni Sangam Holy Bath (Ganga, Yamuna & Saraswati)",
          "Hanuman Mandir & Anand Bhawan Visit",
          "Allahabad Fort (External View)",
          "Overnight Stay in Prayagraj",
        ],
      },
      {
        title: "Day 5 – Prayagraj Sightseeing + Departure",
        items: [
          "Morning Prayag Raj Temple Visit",
          "Local Market & Prasad Shopping",
          "Return Journey to Varanasi",
          "Varanasi Airport / Railway Station Drop",
        ],
      },
    ],
    inclusions: [
      "Hotel Stay in Varanasi, Ayodhya & Prayagraj (1/2/3 Star – Availability के अनुसार)",
      "Pickup & Drop (Airport / Railway Station)",
      "Inter-city Transport (Varanasi ↔ Ayodhya ↔ Prayagraj)",
      "Local Sightseeing Transport",
      "Ganga Boat Ride in Varanasi",
      "Local Guide Assistance (Tour Support)",
    ],
    exclusions: [
      "Food / Meals (Breakfast, Lunch, Dinner शामिल नहीं है)",
      "Temple VIP Pass / Special Darshan (Self Paid)",
      "Personal Expenses (Shopping, Tips, etc.)",
      "Entry Fees (जहाँ applicable हो)",
      "Boat charges at Triveni Sangam (Self Paid, if applicable)",
    ],
    highlights: [
      "5 Days / 4 Nights Complete Spiritual Triangle Tour",
      "Kashi Vishwanath & Ganga Aarti Experience",
      "Sarnath Buddhist Heritage Tour",
      "Shri Ram Janmabhoomi Temple Darshan",
      "Triveni Sangam Holy Bath at Prayagraj",
      "Multi-city Comfortable Travel & Stay",
      "Local Guide Assistance Throughout",
    ],
    cta: "Book your Varanasi – Ayodhya – Prayag Tour and complete the ultimate spiritual journey of Uttar Pradesh.",
  },
];

function getTourBySlug(slug) {
  return TOURS.find((t) => t.slug === slug);
}

// Homepage card data (derived from TOURS)
const DESTINATIONS = TOURS.map((t) => ({
  title: t.title,
  image: t.cardImage,
  duration: t.duration,
  price: `From ${t.price}`,
  url: t.url,
}));
